### PR TITLE
shape detection updates

### PR DESCRIPTION
**Pull request by jmoxrox**

### CODE REVIEW

**Comment by jvillemare** [comment]
Do you mean to add all the image files (`.png`) or no?

**Comment by DarkmatterVale** [comment]
+1 to @jvillemare's comment. LGTM otherwise.

**Review by DarkmatterVale — CHANGES_REQUESTED** [review]
Resolve the question about the images.

**Comment by DarkmatterVale** [comment]
Discussed this over slack, and the images are in there for a new kind of classification.

**Review by DarkmatterVale — APPROVED** [review]

**Pull request merged**
